### ISSUE TITLE
No such file or directory: 'xdg-open' upon clicking Open Activity

### ISSUE THREAD

**Issue by Swanson-Hysell** [sededu/sededu#96]
I followed the installation instructions using conda and am able to run the activities. However, when I click the Open Activity button, I get the following Error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open'
```

Are there additional dependencies that need to be installed and need to be described to the user in the README? Or is the closed issue #77 still an issue on OSX?

**Comment by ericbarefoot** [comment]
Hi @Swanson-Hysell thanks for letting us know. While I'm digging on this, can you tell me what version of OSX you're using? I was trying to reproduce the error, but actually have different problems now due to some changes that Apple made to Xcode, so I can't even get to the issue you're having.

My suspicion is that when OSX updated to whatever the new one is, that it re-broke issue #77, but I am not sure yet.

**Comment by Swanson-Hysell** [comment]
The version of macOS where I am getting the error is Mojave 10.14.6

**Comment by amoodie** [comment]
Hey @Swanson-Hysell, thanks for the notice, and thanks for reviewing the paper. It seems like you've been sent down a wrong if-else branch for some reason, sending you to the Linux executable rather than the OSX executable ([see lines here](https://github.com/sededu/sededu/blob/2cd01c9c015c8b370eb46edf5045419c0f9fcf46/sededu/utilities.py#L115)). I've triggered an OSX build on the CI to try and resolve the issue (v10.13.6, the latest I have available) and I'll try to debug. I'll let you know when I think things have been patched up.

**Comment by amoodie** [comment]
Hi @Swanson-Hysell, I've been trying to track down this bug, but I just can't recreate it on any of the CI systems. It does not seem to be an issue on Mojave 10.14.4 ([build here](https://travis-ci.com/sededu/sededu/builds/150680347), this is the latest version I can build on). You don't have any non-standard platform setup, correct? Nothing with VMs or dual booting with Linux...?

Can you run
```
python3 -c "import platform; print('System:', platform.system()); print('Platform:', platform.platform()); print('module v:', platform.__version__)"
```
in the exact same way you ran `python3 > import sededu > sededu.run()`, and paste the output here? The first line should print `System: Darwin`.

Thanks for your help, I realize this may not be the "review" you signed up for.

**Comment by Swanson-Hysell** [comment]
I don't have VMs or dual booting with Linux. 

I get the error both on a laptop with Mojave and a desktop with Catalina. Here is the info from the desktop with Catalina when running the platform print code:

```
(base) Nicks-iMac:~ Laurentia$ python3 -c "import platform; print('System:', platform.system()); print('Platform:', platform.platform()); print('module v:', platform.__version__)"
System: Darwin
Platform: Darwin-19.3.0-x86_64-i386-64bit
module v: 1.0.8
```
And here is the error related to ```xdg-open``` that happens when I click an open activity button:

```
(base) Nicks-iMac:~ Laurentia$ python3
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57) 
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sededu


    SedEdu -- sediment related activity suite


To run the activity use command:

sededu.run()

>>> sededu.run()
Traceback (most recent call last):
  File "/Users/Laurentia/opt/miniconda3/lib/python3.7/site-packages/sededu/category.py", line 94, in <lambda>
    iModuleDocLaunchButton.clicked.connect(lambda x, lL=iModuleDocLaunchList: iModuleDocList.docLaunch(lL))
  File "/Users/Laurentia/opt/miniconda3/lib/python3.7/site-packages/sededu/category.py", line 177, in docLaunch
    utls.open_file(filename)
  File "/Users/Laurentia/opt/miniconda3/lib/python3.7/site-packages/sededu/utilities.py", line 105, in open_file
    subprocess.Popen(['xdg-open', filename])
  File "/Users/Laurentia/opt/miniconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/Laurentia/opt/miniconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open'
Abort trap: 6
```

**Comment by amoodie** [comment]
Okay @Swanson-Hysell! I think I fixed the problem. There was an out of date key preventing new releases from being uploaded to Conda properly. I should have caught this much earlier, but that's what I get for always working on the dev copy and not actually checking that the releases post.

Anyway, I'm guessing your sededu version is <1.1.2, which is from before #77 was fixed. The latest SedEdu (v1.1.7) is now on conda, so you should be able to upgrade with:
```
conda update -c sededu sededu
```

Thanks for the help and patience. Hopefully this fixes the bug.

**Comment by Swanson-Hysell** [comment]
I can now open activities. Thanks.

Have you considered releasing the software as an executable? As the project is set up, the user is required to do a full scientific Python install (e.g. conda), an install of the package, launching the software from a python environment after an import, but then not having any interaction with the underlying code. In this way, things are set up to have the usual pain points that can come with getting a full class to deal with a Python install without the benefit of students getting experience learning how to deal with code. It seems that if the goal is to have the software be such that students only interact with a GUI that it being released as an executable makes some sense — although I realize that there is a whole host of development challenges associated with making executable releases for different platforms.

**Comment by amoodie** [comment]
Great! Thanks for your help and for closing the issue. 

I have definitely considered it, but never attempted it. When I started reading up on how to make it happen, it seemed like there were going to be a lot of challenges, that I was not equipped to deal with at the time. I've recently received some NSF support to continue developing SedEdu though, and I think deploying as an executable is in scope.
