### ISSUE TITLE
conda install requires Python <3.8 which means that installation instructions are out of date

### ISSUE THREAD

**Issue by Swanson-Hysell** [sededu/sededu#99]
The README tells the user to install Python via Anconda and then conda install the package. However, a user following this installation will get python=3.9 which doesn't appear to be compatible with the sededu conda install. 

For example, when I try:
```
conda install -c sededu sededu
```

I get this error:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - sededu -> python[version='>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8
```

**Comment by amoodie** [comment]
Thank you for pointing this out. Installation instructions are updated with v1.1.10.

I've tested installation:
 * continuous integratation on GitHub Actions, building and testing on linux, windows, and macos with Python 3.7, 3.8, 3.9
 * Manually tested installation with my own linux and windows machines, following installation instructions in the README
